// Generated by CoffeeScript 1.8.0
var IndieAuth, cozydb,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

cozydb = require('cozydb');

module.exports = IndieAuth = (function(_super) {
  __extends(IndieAuth, _super);

  function IndieAuth() {
    return IndieAuth.__super__.constructor.apply(this, arguments);
  }

  IndieAuth.schema = {
    me: String,
    redirect_uri: String,
    client_id: String,
    scope: String,
    response_type: String,
    state: String,
    code: String,
    token: String
  };

  return IndieAuth;

})(cozydb.CozyModel);
